<?php View::template('turismo') ?>
<h1 class="h3">Eventos</h1>
<div class="list-group">
  <?php foreach ($events as $ev): ?>
    <a class="list-group-item list-group-item-action" href="#">
      <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1"><?php echo $ev->title ?></h5>
        <small class="text-muted"><?php echo date('d/m/Y', strtotime($ev->start_date)) ?></small>
      </div>
      <p class="mb-1 small"><?php echo $ev->category ?><?php if($ev->place) echo ' · '.$ev->place; ?></p>
    </a>
  <?php endforeach ?>
</div>
